create table tutores (
    id integer primary key generated by default as identity,
    nome varchar(150) not null,
    telefone varchar(30),
    email varchar(150),
    criado_em date default now()
);

create table veterinarios (
    id integer primary key generated by default as identity,
    nome varchar(150) not null,
    crmv varchar(50) unique,
    especialidade varchar(100),
    ativo bool default True,
    criado_em date default now()
);

create table pets (
    id integer primary key generated by default as identity,
    nome varchar(150) not null,
    especie varchar(50) not null,
    data_nascimento date,
    tutor_id integer,
    criado_em date default now()
);

alter table pets add constraint fk_pets_tutor foreign key (tutor_id) REFERENCES tutores (id);

create table consultas (
    id integer primary key generated by default as identity,
    pet_id integer not null,
    veterinario_id integer not null,
    data_consulta date not null,
    motivo varchar(255),
    valor_consulta numeric(10,2),
    retorno_agendado_em date,
    criado_em date default now()
);

alter table consultas add constraint fk_consultas_pet foreign key (pet_id) REFERENCES pets (id);
alter table consultas add constraint fk_consultas_veterinario foreign key (veterinario_id) REFERENCES veterinarios (id);

INSERT INTO tutores (id, nome, telefone, email, criado_em) VALUES
                                                               (1, 'Marina Alves',        '(21) 98888-0001', 'marina.alves@example.com',        NOW()),
                                                               (2, 'Jorge Matos',         '(21) 98888-0002', 'jorge.matos@example.com',         NOW()),
                                                               (3, 'Bruna Freitas',       '(21) 98888-0003', 'bruna.freitas@example.com',       NOW()),
                                                               (4, 'Cecília Prado',       '(21) 98888-0004', 'cecilia.prado@example.com',       NOW()),
                                                               (5, 'Rafael Araújo',       '(21) 98888-0005', 'rafael.araujo@example.com',       NOW()),
                                                               (6, 'Fabiana Lopes',       '(21) 98888-0006', 'fabiana.lopes@example.com',       NOW()),
                                                               (7, 'Carlos Henrique',     '(21) 98888-0007', 'carlos.henrique@example.com',     NOW()),
                                                               (8, 'Paula Siqueira',      '(21) 98888-0008', 'paula.siqueira@example.com',      NOW()),
                                                               (9, 'Felipe Moreira',      '(21) 98888-0009', 'felipe.moreira@example.com',      NOW()),
                                                               (10,'Juliana Bueno',       '(21) 98888-0010', 'juliana.bueno@example.com',       NOW()),
                                                               (11,'Eduardo Lima',        '(21) 98888-0011', 'eduardo.lima@example.com',        NOW()),
                                                               (12,'Camila Santos',       '(21) 98888-0012', 'camila.santos@example.com',       NOW()),
                                                               (13,'Marcos Vinícius',     '(21) 98888-0013', 'marcos.vinicius@example.com',     NOW()),
                                                               (14,'Larissa Ribeiro',     '(21) 98888-0014', 'larissa.ribeiro@example.com',     NOW()),
                                                               (15,'Renata Silva',        '(21) 98888-0015', 'renata.silva@example.com',        NOW()),
                                                               (16,'Tiago Andrade',       '(21) 98888-0016', 'tiago.andrade@example.com',       NOW()),
                                                               (17,'Sandra Moreira',      '(21) 98888-0017', 'sandra.moreira@example.com',      NOW()),
                                                               (18,'Henrique Souza',      '(21) 98888-0018', 'henrique.souza@example.com',      NOW()),
                                                               (19,'Marta Cardoso',       '(21) 98888-0019', 'marta.cardoso@example.com',       NOW()),
                                                               (20,'Bruno Rezende',       '(21) 98888-0020', 'bruno.rezende@example.com',       NOW());




INSERT INTO veterinarios (id, nome, crmv, especialidade, ativo, criado_em) VALUES
                                                                               (1,  'Ana Paula Nogueira',  'CRMV-RJ-1001', 'Clínico Geral',        TRUE, NOW()),
                                                                               (2,  'Bruno Carvalho',      'CRMV-RJ-1002', 'Cirurgia Geral',       TRUE, NOW()),
                                                                               (3,  'Carla Menezes',       'CRMV-RJ-1003', 'Dermatologia',         TRUE, NOW()),
                                                                               (4,  'Daniel Farias',       'CRMV-RJ-1004', 'Ortopedia',            TRUE, NOW()),
                                                                               (5,  'Elaine Souza',        'CRMV-RJ-1005', 'Oftalmologia',         TRUE, NOW()),
                                                                               (6,  'Fernando Rocha',      'CRMV-RJ-1006', 'Emergência',           TRUE, NOW()),
                                                                               (7,  'Gabriela Torres',     'CRMV-RJ-1007', 'Oncologia',            TRUE, NOW()),
                                                                               (8,  'Henrique Teixeira',   'CRMV-RJ-1008', 'Anestesiologia',       TRUE, NOW()),
                                                                               (9,  'Isabela Martins',     'CRMV-RJ-1009', 'Gatos (Felinos)',      TRUE, NOW()),
                                                                               (10, 'João Victor Lima',    'CRMV-RJ-1010', 'Cães (Caninos)',       TRUE, NOW()),
                                                                               (11, 'Karina Duarte',       'CRMV-RJ-1011', 'Animais Exóticos',     TRUE, NOW()),
                                                                               (12, 'Lucas Almeida',       'CRMV-RJ-1012', 'Clínico Geral',        TRUE, NOW()),
                                                                               (13, 'Mariana Gomes',       'CRMV-RJ-1013', 'Cardiologia',          TRUE, NOW()),
                                                                               (14, 'Nelson Ribeiro',      'CRMV-RJ-1014', 'Neurologia',           TRUE, NOW()),
                                                                               (15, 'Olívia Fernandes',    'CRMV-RJ-1015', 'Endocrinologia',       TRUE, NOW()),
                                                                               (16, 'Pedro Henrique Dias', 'CRMV-RJ-1016', 'Clínico Geral',        TRUE, NOW()),
                                                                               (17, 'Quitéria Barros',     'CRMV-RJ-1017', 'Dermatologia',         TRUE, NOW()),
                                                                               (18, 'Ricardo Monteiro',    'CRMV-RJ-1018', 'Cirurgia Geral',       TRUE, NOW()),
                                                                               (19, 'Simone Freitas',      'CRMV-RJ-1019', 'Gatos (Felinos)',      TRUE, NOW()),
                                                                               (20, 'Thiago Costa',        'CRMV-RJ-1020', 'Animais Silvestres',   TRUE, NOW());




INSERT INTO pets (id, nome, especie, data_nascimento, tutor_id, criado_em) VALUES
                                                                               (1,'Thor','cachorro','2018-05-11',1,NOW()),
                                                                               (2,'Mima','gato','2020-08-22',2,NOW()),
                                                                               (3,'Algodão','coelho','2021-02-10',3,NOW()),
                                                                               (4,'Luna','cachorro','2019-12-01',4,NOW()),
                                                                               (5,'Nino','gato','2017-04-19',5,NOW()),
                                                                               (6,'Pipoca','hamster','2022-01-17',6,NOW()),
                                                                               (7,'Bento','cachorro','2016-09-30',7,NOW()),
                                                                               (8,'Mel','gato','2023-03-05',8,NOW()),
                                                                               (9,'Kiwi','tartaruga','2015-11-12',9,NOW()),
                                                                               (10,'Zara','cachorro','2020-07-14',10,NOW()),
                                                                               (11,'Tico','pássaro','2022-10-03',11,NOW()),
                                                                               (12,'Amora','gato','2019-01-28',12,NOW()),
                                                                               (13,'Frodo','cachorro','2018-06-16',13,NOW()),
                                                                               (14,'Malu','gato','2021-11-09',14,NOW()),
                                                                               (15,'Bolt','cachorro','2017-02-23',15,NOW()),
                                                                               (16,'Sakura','coelho','2020-10-15',16,NOW()),
                                                                               (17,'Loki','gato','2022-05-07',17,NOW()),
                                                                               (18,'Koda','cachorro','2021-04-11',18,NOW()),
                                                                               (19,'Jade','gato','2016-08-08',19,NOW()),
                                                                               (20,'Snow','coelho','2019-09-21',20,NOW());




INSERT INTO consultas (id, pet_id, veterinario_id, data_consulta, motivo, valor_consulta, retorno_agendado_em, criado_em) VALUES
                                                                                                                              (21, 1,  1, '2024-08-05 10:00', 'Vacinação anual',        130.00, NULL, NOW()),
                                                                                                                              (22, 2,  9, '2024-08-07 11:15', 'Retorno alergia',        150.00, NULL, NOW()),
                                                                                                                              (23, 3, 11, '2024-08-10 09:30', 'Vermifugação',           110.00, NULL, NOW()),
                                                                                                                              (24, 4,  4, '2024-08-12 16:00', 'Retorno dor na pata',    180.00, NULL, NOW()),
                                                                                                                              (25, 5, 19, '2024-08-15 14:10', 'Check-up felino',        160.00, NULL, NOW()),
                                                                                                                              (26, 6,  6, '2024-08-18 15:40', 'Crise respiratória',     260.00, '2024-09-01 15:40', NOW()),
                                                                                                                              (27, 7, 10, '2024-08-20 13:20', 'Tosse leve',             140.00, NULL, NOW()),
                                                                                                                              (28, 8,  9, '2024-08-22 10:05', 'Dermatite recorrente',   190.00, '2024-09-22 10:05', NOW()),
                                                                                                                              (29, 9, 20, '2024-08-25 09:10', 'Revisão casco',          130.00, NULL, NOW()),
                                                                                                                              (30,10, 1, '2024-08-28 14:30', 'Vacinação múltipla',      140.00, NULL, NOW()),


                                                                                                                              (31,11,11, '2024-09-02 15:00', 'Queda de penas',          135.00, NULL, NOW()),
                                                                                                                              (32,12,19, '2024-09-05 09:20', 'Infecção ocular',         195.00, '2024-09-19 09:20', NOW()),
                                                                                                                              (33,13,10, '2024-09-07 11:10', 'Dor abdominal',           180.00, NULL, NOW()),
                                                                                                                              (34,14, 9, '2024-09-10 16:15', 'Alergia alimentar',       190.00, NULL, NOW()),
                                                                                                                              (35,15, 1, '2024-09-12 14:00', 'Check-up geriátrico',     150.00, NULL, NOW()),
                                                                                                                              (36,16,11, '2024-09-15 13:40', 'Letargia persistente',    170.00, NULL, NOW()),
                                                                                                                              (37,17,19, '2024-09-18 09:05', 'Gastrite felina',         205.00, NULL, NOW()),
                                                                                                                              (38,18,10, '2024-09-20 10:25', 'Otite canina',            155.00, '2024-10-04 10:25', NOW()),
                                                                                                                              (39,19, 9, '2024-09-23 15:10', 'Dermatite crônica',       200.00, NULL, NOW()),
                                                                                                                              (40,20,20, '2024-09-27 08:50', 'Apatia e perda de apetite', 175.00, NULL, NOW()),


                                                                                                                              (41, 1,  3, '2024-10-01 10:00', 'Coceira nas orelhas',    185.00, NULL, NOW()),
                                                                                                                              (42, 2,  9, '2024-10-03 11:30', 'Dermatite felina',       195.00, '2024-10-24 11:30', NOW()),
                                                                                                                              (43, 3, 11, '2024-10-05 09:15', 'Check-up coelho',        120.00, NULL, NOW()),
                                                                                                                              (44, 4,  4, '2024-10-07 16:00', 'Ortopedia acompanhamento', 220.00, NULL, NOW()),
                                                                                                                              (45, 5, 19, '2024-10-10 14:05', 'Consulta de rotina',     140.00, NULL, NOW()),
                                                                                                                              (46, 6,  6, '2024-10-13 15:30', 'Emergência respiratória', 300.00, '2024-10-20 15:30', NOW()),
                                                                                                                              (47, 7, 10, '2024-10-15 13:20', 'Check-up canino',        135.00, NULL, NOW()),
                                                                                                                              (48, 8,  9, '2024-10-18 10:00', 'Controle de alergia',    175.00, NULL, NOW()),
                                                                                                                              (49, 9, 20, '2024-10-20 09:25', 'Exame em tartaruga',     160.00, NULL, NOW()),
                                                                                                                              (50,10, 1, '2024-10-23 14:45', 'Vacinação reforço',       145.00, NULL, NOW()),


                                                                                                                              (51,11,11, '2024-11-02 15:10', 'Revisão penas',           140.00, NULL, NOW()),
                                                                                                                              (52,12,19, '2024-11-05 09:00', 'Retorno infecção ocular', 180.00, NULL, NOW()),
                                                                                                                              (53,13,10, '2024-11-07 11:35', 'Diarreia aguda',          170.00, NULL, NOW()),
                                                                                                                              (54,14, 9, '2024-11-10 16:20', 'Controle alergia alimentar', 200.00, NULL, NOW()),
                                                                                                                              (55,15, 1, '2024-11-12 14:15', 'Check-up anual',          130.00, NULL, NOW()),
                                                                                                                              (56,16,11, '2024-11-15 13:30', 'Avaliação geral',         150.00, NULL, NOW()),
                                                                                                                              (57,17,19, '2024-11-18 09:40', 'Gastrite leve',           185.00, NULL, NOW()),
                                                                                                                              (58,18,10, '2024-11-20 10:10', 'Otite recorrente',        165.00, '2024-12-04 10:10', NOW()),
                                                                                                                              (59,19, 9, '2024-11-23 15:05', 'Dermatite em remissão',   175.00, NULL, NOW()),
                                                                                                                              (60,20,20, '2024-11-27 08:55', 'Retorno apatia',          160.00, NULL, NOW());

select count(*) as registros from tutores;
select count(*) as registros from veterinarios;
select count(*) as registros from pets;
select count(*) as registros from consultas;

select id, nome, especialidade, ativo from veterinarios order by nome;

select c.id as id_consulta, p.nome as nome_pet, t.nome as nome_tutor, v.nome as nome_veterinario, c.data_consulta, c.motivo from consultas c
    inner join pets p on c.pet_id = p.id
    inner join veterinarios v on c.veterinario_id = v.id
    inner join tutores t on p.tutor_id = t.id order by c.data_consulta desc;

select id, nome, data_nascimento, tutor_id from pets where especie like 'gato' order by data_nascimento;

select c.id, p.nome as nome_pet, v.nome as nome_veterinario, c.data_consulta, c.retorno_agendado_em from consultas c
                                                                                                             inner join pets p on c.pet_id = p.id
                                                                                                             inner join veterinarios v on c.veterinario_id = v.id where c.retorno_agendado_em is not null order by c.retorno_agendado_em desc;

select v.nome as nome_veterinario, count(c.id) as total_consultas from veterinarios v
    left join consultas c on v.id = c.veterinario_id group by v.id having count(c.id) >= 1 order by total_consultas desc;

select t.nome as nome_tutor, count(distinct p.id) as qtde_pets, coalesce(count(c.id),0) as qtde_consultas from tutores t
    inner join pets p on t.id = p.tutor_id
    left join consultas c on p.id = c.pet_id group by t.id order by nome_tutor;

with numeracao_consultas as (
select p.nome as nome_pet,c.data_consulta, row_number() over (partition by p.id order by c.data_consulta desc) as ordem, v.nome as nome_veterinario, c.motivo as motivo from pets p
    inner join consultas c on p.id = c.pet_id
    inner join veterinarios v on c.veterinario_id = v.id)
select nome_pet, data_consulta as data_ultima_consulta, nome_veterinario, motivo from numeracao_consultas where ordem = 1 order by nome_pet;

select p.nome as nome_pet, count(c.id) as qtde_consultas from pets p
    left join consultas c on p.id = c.pet_id group by p.id having count(c.id) > 1 order by qtde_consultas desc;

select v.nome as nome_veterinario, sum(c.valor_consulta) as total_faturado, count(c.id) as qtde_consultas from veterinarios v
    inner join consultas c on v.id = c.veterinario_id group by v.id order by total_faturado desc;

select to_char(date_trunc('month', data_consulta),'YYYY-MM') as ano_mes, count(id) as total_consultas, sum(valor_consulta) as faturamento_mes
from consultas group by date_trunc('month', data_consulta) order by ano_mes;

with ordenamento_fat_mes_vet as (
select date_trunc('month', c.data_consulta) as data, row_number() over (partition by date_trunc('month', c.data_consulta) order by sum(c.valor_consulta) desc) as ordem, v.nome as nome_veterinario, sum(c.valor_consulta) as faturamento_mes_vet from veterinarios v
    inner join consultas c on v.id = c.veterinario_id group by data, nome_veterinario)
select to_char(data,'YYYY-MM') as ano_mes, nome_veterinario, faturamento_mes_vet from ordenamento_fat_mes_vet where ordem = 1 order by ano_mes;

with tutor_consulta_info as (
select t.nome as nome_tutor, count(c.id) as qtde_consultas, sum(c.valor_consulta) as total_gasto from tutores t
    inner join pets p on t.id = p.tutor_id
    left join consultas c on p.id = c.pet_id group by t.id)
select nome_tutor, qtde_consultas, total_gasto, round(100 * total_gasto/sum(total_gasto) over (),2) as percentual_clinica from tutor_consulta_info order by total_gasto desc;